#!/bin/bash

constfile="${HOME}/selector-qa/extras/constitucion.txt"

function ayuda {
	echo -e "Usage: \tce <article> <filename>.txt"
	echo -e "\t:Print article in source file"
	echo -e "\tce <pattern>"
	echo -e "\t:Print ocurriencies of <pattern> in source file"
}

while getopts h opt; do
	case ${opt} in
		h) # ayuda
		   ayuda;exit 0;;
	esac
done
shift $((OPTIND -1))

if [[ "$#" -eq 0 ]]; then
	less $constfile
	exit 1
fi

if [[ ! -z "$2" ]]; then
	constfile=$2
fi

if [ ! -f $constfile  ]; then
	echo "ce (E): Fichero de constitucion no encontrado"
	ayuda
	exit 1;
fi



if [[ "$1" =~ ^[0-9]+$ ]]; then
	grep --color -i -e "^Art*.culo $1\.\|^$1\." $constfile
else 
	grep --color -i $1 $constfile
	
fi
