#!/bin/bash

function ayuda {
	echo "Usage: ce <article> <filename>.txt"
}

if [[ -z "$2" ]]; then
	constfile="${HOME}/oposiciones/extras/constitucion.txt"
else
	constfile=$2
fi

if [ ! -f $constfile  ]; then
	echo "ce (E): Fichero de constitucion no encontrado"
	ayuda
	exit 1;
fi

if [[ "$1" =~ ^[0-9]+$ ]]; then
	grep --color -i -e "^Art*.culo $1\.\|^$1\." $constfile
else 
	grep --color -i $1 $constfile
	
fi
