#!/bin/bash 

#Colors
blue='\033[1;34m'
endColor='\033[0m'
max=20

function ayuda {
	echo "Usage: tabla <filename>.txt"
	echo " :tabla without argument list tables"
}
tablepath="$HOME/oposiciones/extras/tablas"

if [ "$#" -eq 0 ]; then
	ls "$tablepath/"t* | sed 's#.*/##'
	exit 0
fi

while getopts hl opt; do
	case ${opt} in
		h) # ayuda
		   ayuda
		   exit 0;;
		l) # list
		   ls "$tablepath/"t* | sed 's#.*/##'
		   exit 0;;
	esac
done

shift $((OPTIND -1))

# Main

#Comprobar que se pasa un nombre válido de fichero
if [[ $1 =~ \.txt$ ]]; then
	filename=$tablepath'/'$1
else
	filename=$tablepath'/'$1'.txt'
fi

#Comprobar que el fichero pasado como parámetro existe
if [[ ! -f $filename ]]; then
	echo "Tabla (E): Fichero no encontrado"
	ayuda
	exit 1;
fi

less $filename
